### ISSUE TITLE
Gestaltung

### ISSUE THREAD

**Issue by paulactivecinema** [tino-junge/cinema-app#37]
Wichtiges To Do:
- Schriftgröße und Art (Futura...)
- größe des Timers im Bild
  ...ich würde den Timer im Filmbild einbinden (bei uns in der Postproduktion). Ist er eine .gif Vorlage?

**Comment by roschaefer** [comment]
It's not a gif, it's CSS. I guess it's from somewhere [here](https://css-tricks.com/css-pie-timer/), [demo](http://codepen.io/HugoGiraudel/pen/BHEwo).
